// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Restaurant;
//
//    var restaurantUsa = RestaurantUsa.FromJson(jsonString);

namespace Restaurant
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RestaurantUsa
    {
        [JsonProperty("ID")]
        public long Id { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("province")]
        public string Province { get; set; }
    }

    public partial class RestaurantUsa
    {
        public static RestaurantUsa[] FromJson(string json) => JsonConvert.DeserializeObject<RestaurantUsa[]>(json, Restaurant.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this RestaurantUsa[] self) => JsonConvert.SerializeObject(self, Restaurant.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
