// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using USAState;
//
//    var usState = UsState.FromJson(jsonString);

namespace USAState
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UsState
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("abbreviation")]
        public string Abbreviation { get; set; }
    }

    public partial class UsState
    {
        public static List<UsState> FromJson(string json) => JsonConvert.DeserializeObject<List<UsState>>(json, USAState.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<UsState> self) => JsonConvert.SerializeObject(self, USAState.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
